In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import random

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.feature_selection import r_regression
from sklearn.decomposition import PCA

from src.data.utils import get_dataset

C:\Users\MrMil\miniconda3\envs\automl-drug-discovery\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
DATASET = 'AID1445'
DATASET_DIR = DATA_DIR / DATASET
SD_OR_DR = 'SD'

In [ ]:
raw_dataset = _read_data(DATASET_DIR / DATAFILE_NAME)
dataset = HTSDataset(DATASET_DIR, SD_OR_DR)

Processing...
Done!


In [15]:
dr_data = raw_dataset[raw_dataset['DR'].notnull()]

In [ ]:
dr_data.head()

In [16]:
dr_data.describe()

CID          SD  SD Z-score          DR        XC50  \
count  6.550000e+02  655.000000  655.000000  655.000000  655.000000   
mean   2.253767e+07   45.096621    6.377211    4.446591   46.474321   
std    4.542512e+07   15.295037    2.355941    0.356258   35.531813   
min    2.333000e+03   25.953333    3.428512    3.208590    1.000000   
25%    1.942414e+06   33.725000    4.625606    4.204502   24.515000   
50%    3.641576e+06   40.130000    5.612187    4.375409   42.130000   
75%    6.786807e+06   50.910000    7.272663    4.610568   62.445000   
max    1.358460e+08   99.860000   14.812578    6.000000  618.600000   

          # atoms  Max atomic num  
count  655.000000           655.0  
mean    27.267176            53.0  
std      5.194422             0.0  
min     13.000000            53.0  
25%     24.000000            53.0  
50%     27.000000            53.0  
75%     31.000000            53.0  
max     48.000000            53.0

In [19]:
r = r_regression(dr_data['SD'].to_numpy().reshape(-1, 1), dr_data['DR'])

array([0.78330016])

In [72]:
degrees = []
for d in dataset:
    degree = d.edge_index.shape[1] / (2 * d.x.shape[0])
    degrees.append(degree)
pd.DataFrame(degrees).describe()

0
count  207096.000000
mean        1.077867
std         0.033887
min         0.857143
25%         1.052632
50%         1.080000
75%         1.100000
max         1.343750

In [3]:
qm = get_dataset('QM9')

In [5]:
print(qm.data)

Data(x=[2359210, 11], edge_index=[2, 4883516], edge_attr=[4883516, 4], y=[130831, 19], pos=[2359210, 3], z=[2359210], name=[130831], idx=[130831])


In [6]:
ys = qm.data.y

In [8]:
for label in range(ys.shape[1]):
    print(np.histogram(ys[:, label], 10)[0])

[80731 47320  2460   117   125    52    17     7     1     1]
[   13   258  8943 98435 23091    84     5     1     0     1]
[    2     7    74   937 12221 77237 34474  5462   388    29]
[   51  1075  5615 21395 33574 34485 28425  6210     0     1]
[   23   696 19067 57400 45138  8444    58     3     1     1]
[   73  1880 32607 70231 19075  4991  1413   431   115    15]
[   59   937  5279 17066 32966 40251 24106  7749  2038   380]
[    2   114   569 21044 89255 18184  1487   149    21     6]
[    2   114   569 21044 89252 18187  1487   149    21     6]
[    2   114   569 21044 89252 18187  1487   149    21     6]
[    2   114   569 21044 89265 18174  1487   149    21     6]
[    9    37   227  1473 10794 39758 49553 23708  4897   375]
[  393  7215 28767 53021 31817  8177  1262   149    23     7]
[  396  7195 28585 52894 32028  8274  1279   150    23     7]
[  393  7175 28393 52858 32221  8318  1293   150    23     7]
[  440  7226 29998 52945 31220  7616  1217   139    23     7]
[130829 

In [63]:
pd.DataFrame(ys).describe()

0            1            2            3            4   \
count  7211.000000  7211.000000  7211.000000  7211.000000  7211.000000   
mean  -1563.324829     8.774366     0.328628    -9.796747     1.047568   
std     223.693085     2.824833     0.218950     0.957711     1.306775   
min   -2212.566406     3.372320     0.051559   -16.013000    -2.312000   
25%   -1730.527100     6.199356     0.174432   -10.497500     0.079000   
50%   -1570.017700     9.347651     0.293510    -9.774000     0.852000   
75%   -1412.611450    11.214286     0.420955    -9.097000     2.290500   
max    -410.286163    39.694626     3.354865    -7.464000     4.162000   

                5            6            7            8            9   \
count  7211.000000  7211.000000  7211.000000  7211.000000  7211.000000   
mean      5.579421     9.272225    -0.548125    -7.012586    -0.515283   
std       1.865243     0.959624     1.413175     0.630293     0.681024   
min       1.516287     6.931000    -3.986130   -10.948800    -3.805600   
25%       4.268857     8.563580    -1.880315    -7.396650    -0.819300   
50%       4.931407     9.285140    -0.268780    -6.998600    -0.221600   
75%       6.593923     9.909145     0.532850    -6.576750    -0.047350   
max      36.768074    15.725230     2.905550    -5.116400     0.414300   

                10           11           12           13  
count  7211.000000  7211.000000  7211.000000  7211.000000  
mean     -9.091127     0.783564    11.114403    11.882817  
std       0.695896     0.478699     1.341707     1.470614  
min     -14.134100    -1.837600     2.534576     2.432220  
25%      -9.518100     0.730300    10.278284    10.972345  
50%      -9.102900     0.887200    11.132229    11.902810  
75%      -8.619300     0.989700    11.993703    12.894030  
max      -6.981100     1.962400    17.167437    16.456881

In [9]:
pd.DataFrame(ys).describe()

0              1              2              3   \
count  130831.00000  130831.000000  130831.000000  130831.000000   
mean        2.67297      75.281372      -6.536331       0.322046   
std         1.50347       8.173662       0.597721       1.274840   
min         0.00000       6.310000     -11.662800      -4.761992   
25%         1.57780      70.480003      -6.873596      -0.634025   
50%         2.47530      75.599998      -6.560665       0.342863   
75%         3.59635      80.610001      -6.228686       1.385060   
max        29.55640     196.619995      -2.767398       5.265403   

                  4              5              6              7   \
count  130831.000000  130831.000000  130831.000000  130831.000000   
mean        6.858453    1189.409546       4.056910  -11179.626953   
std         1.284146     280.472076       0.901713    1085.385864   
min         0.669400      19.000200       0.434049  -19444.386719   
25%         5.904871    1017.431244       3.418784  -11915.288574   
50%         6.808289    1147.221069       4.044401  -11341.936523   
75%         7.874975    1309.046997       4.663950  -10531.907227   
max        16.928204    3374.753174       7.454396   -1101.487793   

                  8              9              10             11  \
count  130831.000000  130831.000000  130831.000000  130831.000000   
mean   -11179.426758  -11179.408203  -11180.287109      31.620529   
std      1085.377441    1085.377808    1085.403931       4.067535   
min    -19444.171875  -19444.146484  -19445.314453       6.002000   
25%    -11915.072754  -11915.047363  -11916.187500      28.955000   
50%    -11341.719727  -11341.694336  -11342.830078      31.577999   
75%    -10531.656250  -10531.629883  -10532.833984      34.298000   
max     -1101.409790   -1101.384033   -1102.022949      46.969002   

                  12             13             14             15  \
count  130831.000000  130831.000000  130831.000000  130831.000000   
mean      -76.116554     -76.581001     -77.016518     -70.836220   
std        10.323650      10.415005      10.489112       9.498199   
min      -113.113152    -113.891937    -114.611732    -104.816422   
25%       -82.767517     -83.296658     -83.779037     -76.948845   
50%       -76.255539     -76.721046     -77.157455     -70.979301   
75%       -69.459427     -69.858479     -70.248936     -64.737854   
max        -9.240362      -9.278811      -9.330214      -8.733849   

                  16             17             18  
count  130831.000000  130831.000000  130831.000000  
mean        9.965875       1.406731       1.127393  
std      1830.450928       1.600616       1.107332  
min         0.000000       0.337120       0.331180  
25%         2.555040       1.091545       0.911495  
50%         3.090100       1.370650       1.082030  
75%         3.836890       1.655050       1.282720  
max    619867.687500     437.903870     282.945465